apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: python-app
          image: gcr.io/moelzedy/python-app:latest
          ports:
            - containerPort: 8000
          env:
            - name: REDIS_HOST
              value: backend-service